import {spawn} from 'node:child_process';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const [base,advisorId,externalId]=process.argv.slice(2);
if(!/^http:\/\/127\.0\.0\.1:\d+\/$/.test(base))throw Error('Solo servidor temporal local');
const profile=await mkdtemp(path.join(tmpdir(),'fm-qa-chrome-'));
const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless','--disable-gpu','--no-first-run','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{windowsHide:true,stdio:'ignore'});
const watchdog=setTimeout(()=>{console.error('Tiempo máximo de QA excedido');process.exit(1);},90000);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let checks=0;
async function protocol(url){const ws=new WebSocket(url);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});let id=0;const pending=new Map(),events=[];ws.onmessage=e=>{const value=JSON.parse(e.data);if(value.id){const p=pending.get(value.id);pending.delete(value.id);if(value.error)p.reject(Error(value.error.message));else p.resolve(value.result);}else events.push(value);};return {events,close:()=>ws.close(),send:(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));})};}
let browser;const pages=[];
try{
 let portText;for(let i=0;i<100;i++){try{portText=await readFile(path.join(profile,'DevToolsActivePort'),'utf8');break;}catch{await sleep(100);}}
 if(!portText)throw Error('Chrome no inició');const [port,wsPath]=portText.trim().split(/\r?\n/);browser=await protocol('ws://127.0.0.1:'+port+wsPath);
 async function page(){const context=await browser.send('Target.createBrowserContext');const target=await browser.send('Target.createTarget',{url:'about:blank',browserContextId:context.browserContextId});const targets=await (await fetch('http://127.0.0.1:'+port+'/json/list')).json();const p=await protocol(targets.find(t=>t.id===target.targetId).webSocketDebuggerUrl);await p.send('Runtime.enable');await p.send('Page.enable');await p.send('Network.enable');await p.send('Network.setBlockedURLs',{urls:['*apitoken-eeds.onrender.com*','*accounts.google.com*','*gmail.googleapis.com*','*fmglobals.com/api/*']});pages.push(p);return p;}
 async function evaluate(p,expression){const result=await p.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;}
 async function wait(p,expression,label){for(let i=0;i<100;i++){try{if(await evaluate(p,expression)){checks++;console.log('OK '+label);return;}}catch{}await sleep(100);}throw Error(label+' | '+await evaluate(p,"document.body.innerText.slice(-1000)"));}
 async function click(p,selector){await evaluate(p,`document.querySelector(${JSON.stringify(selector)}).click()`);}
 async function fill(p,selector,value){await evaluate(p,`{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));}`);}
 async function select(p,selector,value){await fill(p,selector,value);await evaluate(p,`document.querySelector(${JSON.stringify(selector)}).dispatchEvent(new Event('change',{bubbles:true}))`);}
 async function module(p,id,selector){await click(p,'#'+id);await wait(p,`!!document.querySelector(${JSON.stringify(selector)})`,'Módulo '+id);}
 async function login(p,user){await p.send('Page.navigate',{url:base+'ingresar'});await wait(p,"!!document.querySelector('#usuario')",'Login');await fill(p,'#usuario',user);await fill(p,'#clave','PruebaTemporal123!');await evaluate(p,"document.querySelector('form').requestSubmit()");await wait(p,"!!document.querySelector('.fm-dashboard-proposal')",'Dashboard '+user);}
 async function field(p,label,value){await evaluate(p,`{const l=[...document.querySelectorAll('#spotifyFields label')].find(e=>e.textContent.startsWith(${JSON.stringify(label)}));if(!l)throw Error('Campo '+${JSON.stringify(label)});const e=document.getElementById(l.htmlFor);e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));}`);}
 const admin=await page();await login(admin,'qa_admin');

 await module(admin,'menuUsuarios','#usuariosTable');await click(admin,'#userImport');
 const userCsv='nombre,apellido_paterno,apellido_materno,correo,telefono,usuario,clave,perfil\nImportado QA,Prueba,,qa_import@example.test,+51975554433,qa_csv_import,Temporal123!,Asesor\nDuplicado QA,Prueba,,qa_dup@example.test,+51975554432,qa_csv_import,Temporal123!,Asesor\n';
 await evaluate(admin,`{const dt=new DataTransfer();dt.items.add(new File([${JSON.stringify(userCsv)}],'usuarios.csv',{type:'text/csv'}));document.querySelector('#userCsv').files=dt.files;document.querySelector('#userImportForm').requestSubmit();}`);
 await wait(admin,"document.querySelector('#usersImportReport').textContent.includes('Se importaron 1 registros. Se rechazaron 1 registros.')&&document.querySelector('#userImportModal').classList.contains('show')",'CSV usuarios presenta resumen dentro del modal');
 await wait(admin,"document.querySelector('#usersImportReport button')?.textContent==='Descargar CSV de rechazos'",'CSV usuarios permite descargar rechazos');
 await evaluate(admin,"bootstrap.Modal.getInstance(document.querySelector('#userImportModal')).hide()");await sleep(300);
 await wait(admin,"document.querySelector('#usuariosTable').textContent.includes('qa_csv_import')",'CSV usuarios refresca listado');
 const modules=[['Link','#linkTable'],['Spotify','#spotifyTable'],['Clientes','#clientsTable'],['Activacion','#formActivacion'],['Autoriza','#tablaGmail'],['asesorMenu','#modalAsesor'],['soporteMenu','#modalSoporte'],['GeneradorExterno','#externalGenerateForm'],['menuUsuarios','#usuariosTable'],['menuPermisos','#permissionsForm'],['RestriccionesExterno','#externalRulesForm'],['VentasSpotify','#salesTable'],['reportePublico','table'],['reportesMenu','table'],['reporteSoporte','table'],['reporteLinks','table'],['ReporteExterno','#externalTable']];
 for(const [id,selector] of modules){await module(admin,id,selector);}
 await module(admin,'menuUsuarios','#usuariosTable');await module(admin,'Clientes','#clientsTable');await evaluate(admin,'history.back()');await wait(admin,"!!document.querySelector('#usuariosTable')",'Atrás con URL limpia');await evaluate(admin,'history.forward()');await wait(admin,"!!document.querySelector('#clientsTable')",'Adelante con URL limpia');
 await module(admin,'menuPermisos','#permissionsForm');await wait(admin,"document.querySelector('#permissionModeRole').checked&&!document.querySelector('.permission-preview-group[open]')",'Perfiles por defecto y categorías cerradas');await evaluate(admin,"{const row=document.querySelector('.permission-preview-row');if(row.querySelectorAll('input[type=radio]').length!==2||row.querySelector('[role=switch]'))throw Error('Perfil debe tener dos botones');const input=row.querySelector('input[value=deny]');input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));if(row.dataset.allowed!=='0')throw Error('Acceso no actualizado');}");await click(admin,'label[for=permissionModeUser]');await wait(admin,"document.querySelector('#permissionsForm [name=type]')?.value==='user'",'Permisos por usuario');await select(admin,'.permission-preview-toolbar [name=id]',advisorId);await wait(admin,`document.querySelector('#permissionsForm [name=id]')?.value===${JSON.stringify(advisorId)}&&!location.search`,'Selección sin parámetros');await admin.send('Page.reload');await wait(admin,`document.querySelector('#permissionsForm [name=id]')?.value===${JSON.stringify(advisorId)}&&!location.search`,'Selección conserva al recargar');

 await evaluate(admin,"document.querySelector('#permissionsForm').requestSubmit()");await wait(admin,"!!document.querySelector('.permission-preview')&&document.querySelector('#permissionStatus').textContent.includes('Los cambios se aplican')",'Guardar conserva diseño alternativo');
 await evaluate(admin,`{const radio=document.querySelector('.permission-preview-row input[value="deny"]');radio.checked=true;radio.dispatchEvent(new Event('change',{bubbles:true}));}`);
 await wait(admin,"document.querySelector('.permission-preview-row .permission-final-access').textContent==='Sin acceso'&&document.querySelector('.permission-preview-row .permission-access-source').hidden",'Excepción actualiza acceso final');
 await click(admin,'#restoreProfilePermissions');await wait(admin,"[...document.querySelectorAll('.permission-preview-row input:checked')].every(e=>e.value==='inherit')&&document.querySelector('#permissionStatus').textContent.includes('al guardar')",'Restablecer perfil es vista previa');


 await module(admin,'Clientes','#clientsTable');await click(admin,'#clientNew');await fill(admin,'#clientName','QA navegador');await fill(admin,'#clientPhone','+51971112233');await evaluate(admin,"document.querySelector('#clientForm').requestSubmit()");await wait(admin,"document.querySelector('#clientsTable').textContent.includes('QA navegador')",'Alta cliente real');
 await click(admin,'#clientNew');await fill(admin,'#clientName','Duplicado');await fill(admin,'#clientPhone','+51971112233');await evaluate(admin,"document.querySelector('#clientForm').requestSubmit()");await wait(admin,"!document.querySelector('#clientError').hidden&&document.querySelector('#clientError').textContent.includes('pertenece')",'Duplicado cliente');await evaluate(admin,"bootstrap.Modal.getInstance(document.querySelector('#clientModal')).hide()");await sleep(300);
 await module(admin,'Spotify','#spotifyTable');await fill(admin,'#spotifySearch','qa-one@example.test');await wait(admin,"document.querySelector('#spotifyTable tbody').textContent.includes('qa-one@example.test')&&document.querySelectorAll('#spotifyTable tbody tr').length===1",'Búsqueda Spotify');await click(admin,'[data-spotify-action="assign"]');await field(admin,'Asesor',advisorId);await field(admin,'Inicio del servicio','2026-01-31');await field(admin,'Cantidad de meses','3');await evaluate(admin,"document.querySelector('#spotifyForm').requestSubmit()");await wait(admin,"document.querySelector('#spotifyTable tbody').textContent.includes('30/04/2026')",'Asignación sin cliente tres meses');
 const advisor=await page();await login(advisor,'qa_asesor');await module(advisor,'Spotify','#spotifyTable');await wait(advisor,"document.querySelector('#spotifyTable tbody').textContent.includes('qa-one@example.test')",'Asesor ve asignación');await click(advisor,'[data-spotify-action="renew"]');await field(advisor,'Cantidad de meses','2');await evaluate(advisor,"document.querySelector('#spotifyForm').requestSubmit()");await wait(advisor,"document.querySelector('#spotifyTable tbody').textContent.includes('30/06/2026')",'Renovación dos meses');
 await click(advisor,'[data-spotify-action="transfer"]');await field(advisor,'Celular','+51971112233');await field(advisor,'Nombre','QA navegador');await field(advisor,'Beneficiario','mamá');await evaluate(advisor,"document.querySelector('#spotifyForm').requestSubmit()");await wait(advisor,"document.querySelector('#spotifyTable tbody').textContent.includes('QA navegador (mamá)')",'Vincular beneficiario');
 await click(advisor,'[data-spotify-action="fall"]');await evaluate(advisor,"document.querySelector('#spotifyForm').requestSubmit()");await wait(advisor,"document.querySelector('#spotifyTable tbody').textContent.includes('Caído')",'Caída sigue visible');
 await module(admin,'Spotify','#spotifyTable');await fill(admin,'#spotifySearch','qa-one@example.test');await wait(admin,"!!document.querySelector('[data-spotify-action=rehabilitate]')",'Admin ve caída');await click(admin,'[data-spotify-action="rehabilitate"]');await field(admin,'Correo','qa-restored@example.test');await evaluate(admin,"document.querySelector('#spotifyForm').requestSubmit()");await wait(admin,"document.querySelector('#spotifyNotice').textContent.includes('habilitada')",'Habilitar');
 await module(advisor,'Spotify','#spotifyTable');await wait(advisor,"!document.querySelector('#spotifyNotifications').hidden",'Notificación persistente');await wait(advisor,"document.querySelector('#spotifyTable').textContent.includes('qa-restored@example.test')",'Correo restaurado');
 const external=await page();await login(external,'qa_externo');await wait(external,"!document.querySelector('#ReporteExterno')&&!!document.querySelector('#GeneradorExterno')",'Externo solo servicio');await wait(external,"document.querySelector('.external-home-availability')?.textContent.includes('Servicio habilitado')",'Home muestra estado del generador con permiso');
 await module(admin,'RestriccionesExterno','#externalRulesForm');await wait(admin,"document.querySelector('#externalTargetId').options.length>1",'Configuración cargada');await select(admin,'#externalTargetType','user');await select(admin,'#externalTargetId',externalId);await wait(admin,"!document.querySelector('#externalSave').disabled",'Usuario cargado');await select(admin,'#externalBrowserMode','on');await evaluate(admin,"document.querySelector('#externalRulesForm').requestSubmit()");await wait(admin,"document.querySelector('#externalNotice').textContent.includes('guardadas')",'Restricción navegador guardada');
 await module(external,'GeneradorExterno','#externalGenerateForm');await wait(external,"document.querySelector('#externalRequestBrowser').textContent==='Registrar este navegador'",'Primer registro disponible');await click(external,'#externalRequestBrowser');await wait(external,"!document.querySelector('#externalGenerate').disabled&&document.querySelector('#externalRequestBrowser').hidden",'Primer navegador vinculado');await external.send('Network.deleteCookies',{name:'fm_external_browser',url:base});await external.send('Page.reload');await wait(external,"document.querySelector('#externalGenerate').disabled&&!document.querySelector('#externalRequestBrowser').hidden",'Navegador bloqueado');await click(external,'#externalRequestBrowser');await wait(external,"document.querySelector('#externalRequestBrowser').textContent.includes('pendiente')",'Solicitud navegador');
 await module(external,'inicio','.external-home-availability');await wait(external,"document.querySelector('.external-home-availability').textContent.includes('Pendiente de autorización')&&document.querySelector('.external-home-availability').textContent.includes('Servicio inhabilitado')&&!document.querySelector('[data-open-module=RestriccionesExterno]')",'Home externo muestra bloqueo propio sin alerta administrativa');await module(external,'GeneradorExterno','#externalGenerateForm');
 await module(admin,'inicio','.fm-dashboard-proposal');await wait(admin,"!document.querySelector('.external-home-availability')&&document.querySelector('.proposal-alerts [data-open-module=RestriccionesExterno]')?.textContent.includes('solicitudes de navegador pendientes')",'Home administrativo muestra solicitudes pendientes');await module(admin,'RestriccionesExterno','#externalRulesForm');await wait(admin,"document.querySelector('#externalTargetId').options.length>1",'Restricciones cargadas');await select(admin,'#externalTargetType','user');
 await select(admin,'#externalTargetId',externalId);await wait(admin,"document.querySelector('#externalBrowsers').textContent.includes('Autorizar')",'Admin recibe solicitud');
 await evaluate(admin,"window.confirm=()=>true;[...document.querySelectorAll('#externalBrowsers button')].find(b=>b.textContent==='Autorizar').click()");await wait(admin,"document.querySelector('#externalBrowsers').textContent.includes('Autorizado')",'Aprobación navegador');await external.send('Page.reload');await wait(external,"!document.querySelector('#externalGenerate').disabled",'Navegador habilitado');
 await admin.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await click(admin,'#toggle-btn');await wait(admin,"document.querySelector('#sidebar').classList.contains('active')",'Menú móvil');await click(admin,'#overlay');await wait(admin,"!document.querySelector('#sidebar').classList.contains('active')",'Cierre menú móvil');
 const errors=pages.flatMap(p=>p.events.filter(e=>e.method==='Runtime.exceptionThrown').map(e=>e.params.exceptionDetails.exception?.description||e.params.exceptionDetails.text));if(errors.length)throw Error('Errores JS: '+errors.join('\n'));
 console.log(`CHROME_REAL_PASS: ${checks} comprobaciones con servidor y base temporales.`);
}catch(error){console.log(String(error.stack).slice(0,4000));process.exitCode=1;}finally{clearTimeout(watchdog);for(const p of pages)p.close();browser?.close();chrome.kill();await sleep(500);const resolved=path.resolve(profile);if(resolved.startsWith(path.resolve(tmpdir())+path.sep)&&path.basename(resolved).startsWith('fm-qa-chrome-'))await rm(resolved,{recursive:true,force:true,maxRetries:5,retryDelay:200}).catch(()=>{});}

process.exit(process.exitCode||0);
