<?php
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require dirname(__DIR__).'/bootstrap/app.php';
use FMGlobal\Repositories\{LinkAccountRepository,LinkAccountMigration,PermissionMigration,UserRepository,ScheduleRepository};
use FMGlobal\Services\Links\{AccountVault,AccountImport,LinkGenerator};
use FMGlobal\Http\HttpException;
$config=require FM_ROOT.'/config/database.php';
if(!in_array($config['host'],['localhost','127.0.0.1'],true)||!str_ends_with($config['database'],'_local'))throw new RuntimeException('Requiere base local.');
mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);
$server=new mysqli($config['host'],$config['user'],$config['password']);$name='fm_links_test_'.bin2hex(random_bytes(5));$source=$config['database'];
if(!preg_match('/^[a-zA-Z0-9_]+$/D',$source))throw new RuntimeException('Base inválida.');
$count=0;$temp=tempnam(sys_get_temp_dir(),'links-csv-');
function checkLink(bool $ok,string $label):void{global $count;if(!$ok)throw new RuntimeException($label);$count++;}
function rejectLink(callable $fn,int $status,string $label):void{try{$fn();}catch(HttpException $e){checkLink($e->status===$status,$label);return;}throw new RuntimeException($label);}
try {
 $server->query("CREATE DATABASE `$name` CHARACTER SET utf8mb4");
 foreach(['usuarios','personal','activacion','rol','uso_servicio'] as $table)$server->query("CREATE TABLE `$name`.`$table` LIKE `$source`.`$table`");
 $db=new mysqli($config['host'],$config['user'],$config['password'],$name);$db->set_charset('utf8mb4');
 $db->query("INSERT INTO rol(rol_id,rol_nombre) VALUES(1,'Administrador'),(2,'Asesor'),(3,'Soporte')");PermissionMigration::apply($db);LinkAccountMigration::apply($db);LinkAccountMigration::apply($db);
 $userService=new \FMGlobal\Services\Users\UserService(new UserRepository($db),new ScheduleRepository($db));
 $seed=fn($user,$role)=>['usuario'=>$user,'nombre'=>'Test','apellido_paterno'=>'Test','rol'=>(string)$role,'clave'=>'Temporary test only 123!'];
 $admin=$userService->save($seed('test_admin',1),'test',0);$advisor=$userService->save($seed('test_advisor',2),'test',$admin);$support=$userService->save($seed('test_support',3),'test',$admin);
 foreach([$advisor,$support] as $id)$db->execute_query("INSERT INTO fm_user_permissions(user_id,permission_code,allowed) VALUES(?,'services.links',1)",[$id]);
 $vault=new AccountVault(random_bytes(32));$repo=new LinkAccountRepository($db,$vault);
 $db->execute_query("UPDATE usuarios SET usuario='admin' WHERE id=?",[$admin]);
 checkLink(!in_array($admin,array_column($repo->users($admin),'id'),true),'Admin TI excluido de selectores');
 rejectLink(fn()=>$repo->preview($admin,['operation'=>'assign','target'=>$admin,'quantity'=>1]),422,'No permite asignar a admin TI');
 rejectLink(fn()=>$repo->move($admin,['operation'=>'transfer','source'=>$advisor,'target'=>$admin,'quantity'=>1,'fingerprint'=>'fake']),422,'No permite trasladar a admin TI');

 $legacy='legacy@example.test/pass:with/slash';
 $db->execute_query('INSERT INTO fm_link_accounts(external_id,secure_value,credentials,credential_hash,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW())',[$vault->encrypt('id'),$vault->encrypt('secure'),$vault->encrypt($legacy),$vault->fingerprint($legacy)]);
 $legacyId=$db->insert_id;
 checkLink(\FMGlobal\Repositories\LinkCredentialMigration::apply($db,$vault)===1,'Migra separador anterior');
 checkLink($repo->details($admin,$legacyId)['credentials']==='legacy@example.test:pass:with/slash','No altera contraseña con barras y dos puntos');
 checkLink(\FMGlobal\Repositories\LinkCredentialMigration::apply($db,$vault)===0,'Migración idempotente');
 rejectLink(fn()=>$repo->save($admin,['external_id'=>'id','secure'=>'secure','credentials'=>'legacy@example.test:pass:with/slash']),409,'Hash de duplicados actualizado');
 rejectLink(fn()=>LinkAccountRepository::validate(['external_id'=>'id','secure'=>'secure','credentials'=>'old@example.test/pass']),422,'Formato anterior rechazado');
 $db->execute_query('DELETE FROM fm_link_accounts WHERE id=?',[$legacyId]);
 $db->execute_query("UPDATE personal SET nombre='Ana',apellido_paterno='Ramirez',apellido_materno='Diaz' WHERE usuario_id=?",[$advisor]);
 $named=array_values(array_filter($repo->users($admin),fn($u)=>$u['id']===$advisor))[0];
 checkLink($named['display_name']==='Ana Ramirez Diaz','Selectores muestran nombres completos');
 rejectLink(fn()=>$repo->preview($admin,['operation'=>'transfer','source'=>$advisor,'target'=>$advisor,'quantity'=>1]),422,'Servidor bloquea traslado al mismo usuario');
 $values=['external_id'=>'00123','secure'=>'test-secure','credentials'=>'one@example.test:password/with/slash'];
 $id=$repo->save($admin,$values);$id2=$repo->save($admin,array_replace($values,['credentials'=>'two@example.test:password']));
 checkLink($repo->details($admin,$id)['external_id']==='00123','ID conserva ceros');
 checkLink($repo->listing($admin)['rows'][1]['credentials']===$values['credentials'],'Conserva contraseña con barras');
 $stored=$db->query('SELECT * FROM fm_link_accounts LIMIT 1')->fetch_assoc();checkLink(!str_contains(json_encode($stored),'password')&&!str_contains(json_encode($stored),'test-secure'),'Secretos cifrados');
 checkLink($vault->encrypt('same')!==$vault->encrypt('same'),'IV aleatorio');
 rejectLink(fn()=>$repo->save($admin,$values),409,'Duplicado bloqueado');
 rejectLink(fn()=>$repo->save($advisor,$values),403,'Asesor no crea');
 rejectLink(fn()=>$repo->details($advisor,$id),403,'Asesor no ve ID y secure');
 rejectLink(fn()=>$repo->beginGeneration($advisor,$id),404,'No genera cuentas ajenas');
 checkLink($repo->listing($advisor)['total']===0,'Sin acceso al listado ajeno');
 checkLink($repo->preview($admin,['operation'=>'assign','quantity'=>1,'availability'=>1])['available']===2,'Disponibilidad visible sin elegir destino');
 rejectLink(fn()=>$repo->preview($admin,['operation'=>'assign','quantity'=>1]),422,'Aplicación exige destino válido');
 $move=['operation'=>'assign','target'=>$advisor,'quantity'=>3];$preview=$repo->preview($admin,$move);
 checkLink($preview['available']===2&&$preview['shortage']&&$preview['count']===2,'Falta stock requiere confirmación parcial');
 rejectLink(fn()=>$repo->move($admin,$move),409,'No mueve sin confirmación');
 $repo->move($admin,$move+['fingerprint'=>$preview['fingerprint']]);
 checkLink($repo->listing($advisor)['total']===2&&$repo->listing($support)['total']===0,'Asignación aplica aislamiento');
 checkLink($repo->listing($admin,['q'=>'Ana Ramirez'])['total']===2 && $repo->listing($advisor)['rows'][0]['display_name']==='Ana Ramirez Diaz','Tabla busca y muestra nombre sin cambiar propietario');
 rejectLink(fn()=>$repo->move($admin,$move+['fingerprint'=>$preview['fingerprint']]),409,'Confirmación antigua no reasigna');
 rejectLink(fn()=>$repo->preview($advisor,$move),403,'Asesor no asigna');
 $revision=$repo->details($admin,$id)['revision'];
 rejectLink(fn()=>$repo->markError($advisor,$id,$revision),403,'Asesor no puede marcar error manual');
 $repo->markError($admin,$id,$revision);
 checkLink($repo->listing($admin,['status'=>'manual_error'])['total']===1 && $repo->listing($admin,['status'=>'no_link'])['total']===0,'Error manual usa código 2 y filtro propio');
 $single=$repo->preview($admin,['operation'=>'transfer','source'=>$advisor,'target'=>$support,'account_id'=>$id]);
 checkLink($single['available']===1 && $single['error_type']===2,'Cuenta individual con error no necesita check');
 $db->execute_query('UPDATE fm_link_accounts SET error_type=0 WHERE id=?',[$id]);LinkAccountMigration::apply($db);LinkAccountMigration::apply($db);
 checkLink($repo->listing($admin,['status'=>'manual_error'])['total']===1,'Migración recupera error manual desde auditoría sin duplicar');
 rejectLink(fn()=>$repo->markError($admin,$id,$revision),409,'Estado protege revisiones');
 $transfer=['operation'=>'transfer','source'=>$advisor,'target'=>$support,'quantity'=>'all'];$p=$repo->preview($admin,$transfer);checkLink($p['available']===1,'Error excluido por defecto');
 $p=$repo->preview($admin,$transfer+['include_error'=>1]);checkLink($p['available']===2,'Check incluye error');
 $repo->move($admin,$transfer+['include_error'=>1,'fingerprint'=>$p['fingerprint']]);
 checkLink($repo->listing($advisor)['total']===0&&$repo->listing($support)['total']===2,'Traslado directo');
 $assigned=$db->execute_query('SELECT * FROM fm_link_accounts WHERE id=?',[$id])->fetch_assoc();checkLink((int)$assigned['moved_by']===$admin&&$assigned['assigned_at']!==null,'Movimiento registra actor y fecha');
 $generation=$repo->beginGeneration($support,$id);
 rejectLink(fn()=>$repo->beginGeneration($support,$id),409,'Bloquea generación simultánea');
 rejectLink(fn()=>$repo->save($admin,$values+['id'=>$id,'revision'=>$repo->details($admin,$id)['revision']]),409,'No edita durante generación');
 $release=['operation'=>'release','source'=>$support,'quantity'=>'all','include_error'=>1];checkLink($repo->preview($admin,$release)['available']===1,'No mueve cuentas generando');
 $repo->finishGeneration($support,$id,$generation['token'],true);checkLink($repo->summary($support)['active']===2,'Generación exitosa recupera estado');
 checkLink((int)$db->execute_query('SELECT error_type FROM fm_link_accounts WHERE id=?',[$id])->fetch_assoc()['error_type']===0,'Éxito limpia el tipo de error');
 checkLink($repo->summary($admin)['generated']===1 && (int)$repo->summary($admin)['generators'][0]['total']===1,'Dashboard cuenta generaciones por usuario');
 checkLink($repo->summary($advisor)['generated']===0 && $repo->summary($support)['generated']===1,'Dashboard restringe generaciones a su usuario');
 $generation=$repo->beginGeneration($support,$id);$repo->finishGeneration($support,$id,$generation['token'],false);checkLink($repo->summary($support)['errors']===1,'Generación fallida marca Error');
 checkLink($repo->listing($admin,['status'=>'no_link'])['total']===1 && $repo->listing($admin,['status'=>'manual_error'])['total']===0,'Fallo automático usa código 1 y etiqueta No Link');
 $db->execute_query('UPDATE fm_link_accounts SET error_type=0 WHERE id=?',[$id]);LinkAccountMigration::apply($db);
 checkLink($repo->listing($admin,['status'=>'no_link'])['total']===1,'Migración reconstruye el último fallo automático');
 $attemptSummary=$repo->summary($support);
 checkLink($attemptSummary['generated']===2 && array_sum($attemptSummary['generationSeries'])===2,'Dashboard incluye intento fallido en total y barras');
 checkLink((int)$attemptSummary['generators'][0]['total']===2 && $repo->summary($advisor)['generated']===0,'Intento fallido pertenece solo a su actor');
 checkLink($repo->summary($admin)['generated']===2,'Administrador ve todos los intentos sin duplicar éxitos');

 $db->execute_query("UPDATE fm_user_permissions SET allowed=0 WHERE user_id=? AND permission_code='services.links'",[$support]);
 checkLink($repo->users($admin)[0]['id']===$support,'Usuarios con cuentas sin permiso primero');
 checkLink($repo->summary($admin)['orphaned']===2,'Alerta por pérdida de permiso');rejectLink(fn()=>$repo->listing($support),403,'Permiso revocado bloquea listado');
 rejectLink(fn()=>$repo->preview($admin,['operation'=>'transfer','source'=>$advisor,'target'=>$support,'quantity'=>1]),422,'Destino sin permiso no válido');
 $p=$repo->preview($admin,$release);$repo->move($admin,$release+['fingerprint'=>$p['fingerprint']]);checkLink($repo->summary($admin)['unassigned']===2,'Libera usuarios sin acceso');
 $row=$db->execute_query('SELECT assigned_at,moved_at FROM fm_link_accounts WHERE id=?',[$id])->fetch_assoc();checkLink($row['assigned_at']===null&&$row['moved_at']!==null,'Liberación conserva fecha movimiento');
 file_put_contents($temp,"ID,secure,correo_contrasena\n003,secure,three@example.test:pass\n004,secure,three@example.test:pass\n005,secure,invalid\n");
 $result=(new AccountImport($repo))->run($admin,$temp);checkLink($result['loaded']===1&&$result['rejected']===2&&$result['errors'][0]['row']===3,'Importación parcial informa filas');
 checkLink($result['errors'][0]['email']==='three@example.test' && $result['errors'][0]['data']===['004','secure','three@example.test:pass'],'Informe privado de rechazo devuelve correo y fila completa');
 rejectLink(fn()=>(new AccountImport($repo))->run($advisor,$temp),403,'Asesor no importa');
 file_put_contents($temp,"otro,formato\n");rejectLink(fn()=>(new AccountImport($repo))->run($admin,$temp),422,'CSV valida encabezados');
 $result=(new LinkGenerator(fn($body)=>['status'=>200,'body'=>json_encode(['status'=>'success','login_url'=>'https://www.netflix.com/test-link','expires_at'=>'later'])]))->generate('id','secure');checkLink($result['url']==='https://www.netflix.com/test-link','Generador valida éxito');
 rejectLink(fn()=>(new LinkGenerator(fn($body)=>['status'=>200,'body'=>'{}']))->generate('id','secure'),502,'Respuesta vacía falla');
 rejectLink(fn()=>(new LinkGenerator(fn($body)=>['status'=>200,'body'=>json_encode(['status'=>'success','login_url'=>'javascript:alert(1)'])]))->generate('id','secure'),502,'No acepta URL ejecutable');
 rejectLink(fn()=>(new LinkGenerator(fn($body)=>['status'=>0,'body'=>'']))->generate('id','secure'),502,'Timeout falla');

 $db->execute_query("INSERT INTO fm_user_permissions(user_id,permission_code,allowed) VALUES(?,'reports.links',1)",[$support]);
 checkLink($repo->consultations($support)['generated']===2,'Solo permiso reporte permite tarjeta Consultas link propia');
 rejectLink(fn()=>$repo->summary($support),403,'Solo reporte no permite inventario Link');
 $reportRepo=new \FMGlobal\Repositories\LinkReportRepository($db,$vault);
 $report=$reportRepo->report(null,30,'',1,20);
 checkLink($report['total']===2 && array_sum(array_column($report['rows'],'generated'))===1,'Reporte incluye éxitos y fallos');
 checkLink(array_sum(array_map('array_sum',$report['series']))===$report['total'],'Gráfico y tabla cuentan mismos intentos');
 checkLink(count(current($report['series']))===1,'Gráfico de links usa una sola serie de intentos');
 checkLink($reportRepo->report($advisor,30,'',1,20)['total']===0 && $reportRepo->report($support,30,'',1,20)['total']===2,'Reporte limita por actor');
 checkLink($reportRepo->report(null,30,'No generado',1,20)['total']===1,'Filtro resultado compartido');
 checkLink(!str_contains(json_encode($report),'password'),'Reporte nunca expone contraseñas');
 checkLink((int)$db->query('SELECT COUNT(*) n FROM fm_link_audit')->fetch_assoc()['n']>=10,'Auditoría persistida');
 checkLink(!str_contains(json_encode($db->query('SELECT * FROM fm_link_audit')->fetch_all(MYSQLI_ASSOC)),'password'),'Auditoría no guarda secretos');
 // Una generación vencida no puede sobrescribir un movimiento posterior.
 $generation=$repo->beginGeneration($admin,$id);$db->execute_query('UPDATE fm_link_accounts SET generation_until=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE id=?',[$id]);
 $move=['operation'=>'assign','target'=>$advisor,'quantity'=>1,'account_id'=>$id,'include_error'=>1];$p=$repo->preview($admin,$move);$repo->move($admin,$move+['fingerprint'=>$p['fingerprint']]);
 rejectLink(fn()=>$repo->finishGeneration($admin,$id,$generation['token'],true),409,'Resultado obsoleto no modifica cuenta');
 echo "$count comprobaciones de cuentas correctas, en base temporal y sin API externa.\n";
}finally{if(isset($db))$db->close();$server->query("DROP DATABASE IF EXISTS `$name`");$server->close();unlink($temp);}
