<?php
return array (
  'gestion/clientes.php'=>'app/Controllers/Clients/index.php',
  'reportes/ventas-spotify.php'=>'app/Controllers/Reports/spotify-sales.php',
  'session.php' => 'app/Controllers/Auth/session.php',
  'permisos/save.php' => 'app/Controllers/Permissions/save.php',
  'permisos/index.php' => 'app/Controllers/Permissions/index.php',
  'dashboard.php' => 'app/Controllers/Dashboard/summary.php',
  'home.php' => 'app/Controllers/Dashboard/home.php',
  'inicio.php' => 'app/Controllers/Reports/public.php',
  'login.php' => 'app/Controllers/Auth/login.php',
  'logout.php' => 'app/Controllers/Auth/logout.php',
  'validacion.php' => 'app/Controllers/Consultations/public.php',
  'mantenimiento_gmail.php' => 'app/Controllers/Gmail/index.php',
  'oauth_gmail.php' => 'app/Controllers/Gmail/authorize.php',
  'oauth2callback.php' => 'app/Controllers/Gmail/callback.php',
  'usuario/usuarios.php' => 'app/Controllers/Users/index.php',
  'usuario/usuario_list.php' => 'app/Controllers/Users/list.php',
  'usuario/usuario_get.php' => 'app/Controllers/Users/show.php',
  'usuario/usuario_save.php' => 'app/Controllers/Users/save.php',
  'usuario/usuario_toggle.php' => 'app/Controllers/Users/toggle.php',
  'activacion/activacion.php' => 'app/Controllers/Schedules/index.php',
  'activacion/actualizar_activacion.php' => 'app/Controllers/Schedules/update.php',
  'soporte/asesor.php' => 'app/Controllers/Consultations/advisor.php',
  'soporte/soporte.php' => 'app/Controllers/Consultations/support.php',
  'gestion/spotify.php' => 'app/Controllers/Spotify/index.php',
  'soporte/link.php' => 'app/Controllers/Links/index.php',
  'soporte/reportes.php' => 'app/Controllers/Reports/internal.php',
  'soporte/procesar_disney.php' => 'app/Controllers/Consultations/disney.php',
  'soporte/procesar_netflix1.php' => 'app/Controllers/Consultations/netflix-link.php',
  'soporte/procesar_netflix2.php' => 'app/Controllers/Consultations/netflix-otp.php',
  'soporte/procesar_soporte.php' => 'app/Controllers/Consultations/messages.php',
  'api/buscar_correo.php' => 'app/Controllers/Api/messages.php',
  'api/disney_otp.php' => 'app/Controllers/Api/disney.php',
  'api/netflix_link.php' => 'app/Controllers/Api/netflix-link.php',
  'api/netflix_otp.php' => 'app/Controllers/Api/netflix-otp.php',
);
