<section class="contenedor gmail-page" id="clientsModule">
 <div class="module-heading"><h2>Clientes</h2><span class="module-category">Gestión</span></div>
 <div id="clientsNotice" class="alert" role="status" hidden></div>
 <div class="card card-body"><div class="section-toolbar link-toolbar"><button type="button" class="btn btn-sm btn-primary table-add" id="clientNew">Agregar cliente <i class="fas fa-plus" aria-hidden="true"></i></button><button type="button" class="btn btn-sm btn-outline-primary" id="clientImport">Importar CSV</button></div>
 <div class="tablaOpciones"><input type="search" id="clientsSearch" maxlength="100" class="form-control form-control-sm" placeholder="Buscar nombre o celular" aria-label="Buscar cliente"><select id="clientsSize" class="form-select form-select-sm selectRegistros" aria-label="Registros por página"><option value="10">10 registros</option><option value="20" selected>20 registros</option><option value="50">50 registros</option></select></div>
 <div class="table-responsive"><table id="clientsTable" class="tabla table table-sm table-hover align-middle"><thead><tr><th>Nombre</th><th>Celular</th><th>Acción</th></tr></thead><tbody></tbody></table></div>
 <div class="table-footer"><span id="clientsCount" class="small text-body-secondary"></span><div id="clientsPages" class="paginacion"></div></div></div>
 <div class="modal fade" id="clientModal" tabindex="-1" aria-labelledby="clientTitle" data-bs-backdrop="static"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h3 class="modal-title fs-5" id="clientTitle">Agregar cliente</h3><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div>
 <form id="clientForm"><div class="modal-body"><div id="clientError" class="alert alert-danger" role="alert" hidden></div><div class="fm-fields-grid"><div><label for="clientName" class="form-label">Nombre <span class="text-danger">*</span></label><input id="clientName" class="form-control form-control-sm" required maxlength="150" autocomplete="name"></div><div><label for="clientPhone" class="form-label">Celular <span class="text-danger">*</span></label><input id="clientPhone" type="tel" class="form-control form-control-sm" required maxlength="40" placeholder="+51987654321" autocomplete="tel"><small class="form-text">Incluye + y código de país.</small></div></div></div><div class="modal-footer"><button type="button" class="btn btn-sm btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button><button type="submit" class="btn btn-sm btn-primary" id="clientSave">Guardar</button></div></form></div></div></div>

 <div class="modal fade" id="clientImportModal" tabindex="-1" aria-labelledby="clientImportTitle" data-bs-backdrop="static"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h3 class="modal-title fs-5" id="clientImportTitle">Importar clientes</h3><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><form id="clientImportForm"><div class="modal-body"><div id="clientImportError" class="alert alert-danger" hidden></div><div class="fm-import-heading"><label for="clientCsv" class="form-label">Archivo CSV <span class="text-danger">*</span></label><a href="gestion/clientes.php?action=template" download="clientes-modelo.csv" class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-download" aria-hidden="true"></i> Descargar modelo</a></div><input id="clientCsv" type="file" accept=".csv,text/csv" class="form-control form-control-sm" required aria-describedby="clientCsvHelp"><div id="clientCsvHelp" class="fm-import-help"><div class="fm-import-limits"><span>UTF-8</span><span>Máx. 2 MB</span><span>Hasta 500 filas</span></div><div class="fm-import-format"><span>Columnas</span><code>nombre</code><code>celular</code></div><p>Incluye + y código de país en el celular. Se importan las filas válidas sin sobrescribir clientes existentes.</p></div><div id="clientsImportReport" class="fm-import-result" role="status" hidden></div></div><div class="modal-footer"><button type="button" class="btn btn-sm btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button><button type="submit" class="btn btn-sm btn-primary" id="clientImportSubmit">Importar</button></div></form></div></div></div>
 <div class="modal fade" id="clientInfoModal" tabindex="-1" aria-labelledby="clientInfoTitle"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content">
 <div class="modal-header"><h3 class="modal-title" id="clientInfoTitle">Información del cliente</h3><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div>
 <div class="modal-body"><div id="clientInfoError" class="alert alert-danger" role="alert" hidden></div><div id="clientInfoBusy" role="status" hidden>Cargando servicios…</div>
 <div class="client-info-heading"><strong id="clientInfoName"></strong><span id="clientInfoPhone" class="text-body-secondary"></span></div>
 <p class="small text-body-secondary mb-2">Servicios actuales e historial. El próximo pago corresponde al vencimiento del servicio del cliente.</p>
 <div class="table-responsive"><table class="table table-sm table-hover align-middle" id="clientServicesTable"><thead><tr><th>Servicio</th><th>Correo de cuenta</th><th>Beneficiario</th><th>Inicio</th><th>Próximo pago</th><th>Días por vencer</th><th>Estado</th><th>Liberación</th></tr></thead><tbody></tbody></table></div>
 <div class="table-footer"><small id="clientServicesCount"></small><div id="clientServicesPages" class="paginacion"></div></div></div>
 <div class="modal-footer"><button type="button" class="btn btn-sm btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button></div>
 </div></div></div>
</section>
