<?php $escape=fn($s)=>htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8'); $services=[1=>'Netflix clientes',2=>'Disney clientes',3=>'Netflix · Estoy de viaje',4=>'Disney · Acceso único',5=>'Netflix · Inicio de sesión',6=>'Soporte',7=>'Link Netflix']; $links=$reportKind==='links'; ?>
<section><div class="module-heading"><h2><?= $escape($reportTitle) ?></h2><span class="module-category">Reportes</span></div><p class="section-description"><?= $user===null?'Actividad de todos en los servicios autorizados.':'Solo tu actividad en los servicios autorizados.' ?></p>
<form class="filtros" data-module-filter="<?= $route ?>">
<?php if($fromDashboard): ?><input type="hidden" name="report" value="<?= $escape($reportKind) ?>"><?php endif ?>
<label>Período <select class="form-select form-select-sm" name="days"><?php foreach([7=>'7 días',30=>'30 días',90=>'90 días',0=>'Todo el historial'] as $value=>$label): ?><option value="<?= $value ?>" <?= $days===$value?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label><button class="btn btn-sm btn-primary">Aplicar</button></form>
<div class="cardHome card card-body"><h3><?= (int)$summary['total'] ?> <?= $links?'links generados':'consultas' ?><?php if(!$links): ?> · <?= (int)$summary['results'] ?> resultados<?php endif ?></h3><p>Tendencia de los últimos 30 días</p><?= \FMGlobal\Support\Sparkline::render($series) ?></div>
<div class="tablaContainer table-responsive"><table class="tabla table table-sm table-hover align-middle"><thead><tr><th>Fecha</th><?php if(!$links): ?><th>Correo</th><?php endif ?><th>Servicio</th><th><?= $links?'Links':'Resultados' ?></th><th>Usuario</th></tr></thead><tbody>
<?php foreach($rows as $row): ?><tr><td><?= $escape(\FMGlobal\Support\DisplayDate::dateTime($row['fecha'])) ?></td><?php if(!$links): ?><td><?= $escape($row['correo']) ?></td><?php endif ?><td><?= $escape($services[(int)$row['streaming']]??'Servicio') ?></td><td><?= (int)$row['num_urls'] ?></td><td><?= $escape($row['display_name']??$row['usuario']??'Clientes') ?></td></tr><?php endforeach ?>
<?php if(!$rows): ?><tr><td colspan="<?= $links?4:5 ?>">Sin actividad para este período y tus permisos actuales.</td></tr><?php endif ?></tbody></table></div>
<div class="paginacion"><span>Página <?= $page ?> · 50 registros por página</span><?php if($page>1): ?><button class="pagination-button btn btn-sm btn-outline-primary" data-load-url="<?= $escape($pageUrl($page-1)) ?>">Anterior</button><?php endif ?><?php if($page*50<(int)$summary['total']): ?><button class="pagination-button btn btn-sm btn-outline-primary" data-load-url="<?= $escape($pageUrl($page+1)) ?>">Siguiente</button><?php endif ?></div></section>