<section class="contenedor gmail-page" id="spotifySalesReport">
 <div class="module-heading"><h2>Ventas Spotify</h2><span class="module-category">Reportes</span></div>
 <div id="salesError" class="alert alert-danger" role="alert" hidden></div>
 <div class="card card-body"><div id="salesLegend" class="d-flex justify-content-center flex-wrap gap-3 small mb-2"></div><div id="salesChart" class="sales-chart" role="region" aria-label="Evolución diaria de ventas, renovaciones, pérdidas y caídas" tabindex="0"></div>
 <div class="tablaOpciones sales-filters mt-3"><input id="salesSearch" type="search" class="form-control form-control-sm" maxlength="100" placeholder="Buscar vendedor" aria-label="Buscar vendedor"><select id="salesPeriod" class="form-select form-select-sm" aria-label="Periodo"><option value="today">Hoy</option><option value="week">Última semana</option><option value="month" selected>Último mes</option><option value="six">Últimos 6 meses</option><option value="year">Último año</option><option value="custom">Fechas específicas</option></select><div id="salesCustom" class="sales-date-filters"><div><label class="form-label" for="salesFrom">Fecha de inicio</label><input id="salesFrom" type="date" class="form-control form-control-sm"></div><div><label class="form-label" for="salesTo">Fecha de fin</label><input id="salesTo" type="date" class="form-control form-control-sm"></div></div><select id="salesSize" class="form-select form-select-sm" aria-label="Registros por página"><option value="10">10 registros</option><option value="20" selected>20 registros</option><option value="50">50 registros</option></select></div>
 <div id="salesRange" class="small text-body-secondary mb-2"></div>
 <div class="table-responsive"><table class="tabla table table-sm table-hover align-middle" id="salesTable"><thead><tr><th>Vendedor</th><th>Ventas</th><th>Renovaciones</th><th>Pérdidas de clientes</th><th>Cuentas caídas</th></tr></thead><tbody></tbody><tfoot></tfoot></table></div>
 <div class="table-footer"><span id="salesCount" class="small text-body-secondary"></span><div id="salesPages" class="paginacion"></div></div></div>
</section>
