<?php
use FMGlobal\Http\HttpException;
$expectedEmail=\FMGlobal\Security\OAuthState::consume($_GET['state']??null);
$code=\FMGlobal\Support\Input::text($_GET,'code',4096,true);
$client=new Google_Client();
$client->setAuthConfig(FM_ROOT.'/config/credentials.json');
$client->setRedirectUri('https://fmglobals.com/oauth2callback.php');
$client->addScope(Google_Service_Gmail::GMAIL_READONLY);
$client->setAccessType('offline');
$client->setPrompt('consent');
$client->setHttpClient(new \GuzzleHttp\Client(['timeout'=>20,'connect_timeout'=>5]));
$token=$client->fetchAccessTokenWithAuthCode($code);
if (!is_array($token) || isset($token['error'])) throw new HttpException(502,'No se pudo autorizar Gmail. Inténtalo nuevamente.');
$client->setAccessToken($token);
$gmail=new Google_Service_Gmail($client);
$correo=$gmail->users->getProfile('me')->getEmailAddress();
if ($expectedEmail!==null && strcasecmp($expectedEmail,$correo)!==0) throw new HttpException(400,'La cuenta autorizada no coincide con el correo que deseas actualizar. Vuelve a intentarlo con la cuenta correcta.');
if (empty($token['refresh_token'])) throw new HttpException(400,'No se recibió autorización permanente. Revoca los permisos y vuelve a autorizar.');
(new \FMGlobal\Repositories\GmailTokenRepository(database()))->save($correo,$token['refresh_token']);
$_SESSION['mensaje_gmail']='Correo autorizado correctamente';
header('Location: home.php?modulo=autoriza');
exit;
